import { neon } from '@neondatabase/serverless';
import fs from 'fs';
import path from 'path';

// Parsear .env.development.local manualmente
const envPath = path.resolve(process.cwd(), '.env.development.local');
let databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl && fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  const match = envContent.match(/^DATABASE_URL=["']?([^"'\r\n]+)["']?/m);
  if (match) {
    databaseUrl = match[1];
  }
}

if (!databaseUrl) {
  console.error("Error: No se encontró DATABASE_URL en el entorno ni en .env.development.local");
  process.exit(1);
}

console.log("Conectando a Neon DB...");
const sql = neon(databaseUrl);

async function run() {
  try {
    console.log("Creando tabla 'categories' si no existe...");
    await sql(`
      CREATE TABLE IF NOT EXISTS categories (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT UNIQUE NOT NULL,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
      );
    `);

    console.log("Creando tabla 'admin_settings' si no existe...");
    await sql(`
      CREATE TABLE IF NOT EXISTS admin_settings (
          id INT PRIMARY KEY,
          password_hash TEXT NOT NULL,
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
      );
    `);

    console.log("Creando tabla 'products' si no existe...");
    await sql(`
      CREATE TABLE IF NOT EXISTS products (
          id BIGINT PRIMARY KEY,
          name TEXT NOT NULL,
          category TEXT NOT NULL REFERENCES categories(name) ON UPDATE CASCADE,
          price NUMERIC NOT NULL,
          compare_at_price NUMERIC NULL,
          description TEXT,
          images TEXT[] DEFAULT '{}'::TEXT[],
          tags TEXT[] DEFAULT '{}'::TEXT[],
          stock INTEGER DEFAULT 0,
          brand TEXT DEFAULT 'MEGALODON',
          variants TEXT[] DEFAULT '{}'::TEXT[],
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
      );
    `);

    console.log("Tablas creadas exitosamente.");

    // Check if categories are empty, if so seed them
    const existingCats = await sql('SELECT count(*) as count FROM categories');
    if (parseInt(existingCats[0].count) === 0) {
      console.log("Poblando categorías iniciales...");
      const defaultCats = ['Ceras', 'Apparel', 'Accesorios'];
      for (const name of defaultCats) {
        await sql('INSERT INTO categories (name) VALUES ($1) ON CONFLICT (name) DO NOTHING', [name]);
      }
    }

    // Check if products are empty, if so seed them
    const existingProds = await sql('SELECT count(*) as count FROM products');
    if (parseInt(existingProds[0].count) === 0) {
      console.log("Poblando productos iniciales...");
      const defaultProducts = [
        { id: 1, name: 'Cold Water Wax', category: 'Ceras', price: 4990, compareAtPrice: null, description: 'Fórmula artesanal 100% natural. Grip brutal para el Pacífico chileno.', images: ['wax_1.png'], tags: ['best seller'], stock: 50, brand: 'MEGALODON', variants: [] },
        { id: 2, name: 'Cool Water Wax', category: 'Ceras', price: 4990, compareAtPrice: null, description: 'Para los días de verano. Más firme, ideal para agua fresca y viajes al norte.', images: ['wax_2.png'], tags: ['nuevo'], stock: 40, brand: 'MEGALODON', variants: [] },
        { id: 3, name: 'Surf Pack: 3 Barras', category: 'Ceras', price: 12900, compareAtPrice: 14970, description: 'Lleva 3 barras y ahorra. El pack perfecto para el surfer que siempre quiere tener el mejor grip asegurado.', images: ['wax_3.png'], tags: ['ahorro', 'oferta'], stock: 30, brand: 'MEGALODON', variants: [] },
        { id: 4, name: 'Polera Megalodon', category: 'Apparel', price: 18990, compareAtPrice: 24990, description: 'Camiseta premium de corte oversize en algodón pesado. Hecha para el post-surf. Diseño exclusivo Megalodon.', images: ['bf88c491-03e3-42bd-8b4b-edc8245bcec8.png'], tags: ['apparel'], stock: 20, brand: 'MEGALODON', variants: ['S', 'M', 'L', 'XL'] },
        { id: 5, name: "Leash 9' Megalodon", category: 'Accesorios', price: 14990, compareAtPrice: 19990, description: "Leash ultra resistente de 7mm de uretano premium para olas de hasta 2 metros.", images: ['leash_9.png'], tags: ['accesorios'], stock: 15, brand: 'MEGALODON', variants: [] }
      ];

      for (const p of defaultProducts) {
        await sql(`
          INSERT INTO products (id, name, category, price, compare_at_price, description, images, tags, stock, brand, variants)
          VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
          ON CONFLICT (id) DO NOTHING
        `, [
          p.id,
          p.name,
          p.category,
          p.price,
          p.compareAtPrice,
          p.description,
          p.images,
          p.tags,
          p.stock,
          p.brand,
          p.variants
        ]);
      }
    }

    console.log("Base de datos inicializada correctamente.");
    
    // Configurar contraseña inicial si admin_settings está vacío
    const existingAdmin = await sql('SELECT count(*) as count FROM admin_settings');
    if (parseInt(existingAdmin[0].count) === 0) {
      console.log("Configurando contraseña de admin por defecto...");
      const crypto = await import('crypto');
      const defaultPass = process.env.ADMIN_PASSWORD || 'Surfwax';
      const defaultHash = crypto.createHash('sha256').update(defaultPass).digest('hex');
      await sql('INSERT INTO admin_settings (id, password_hash) VALUES (1, $1)', [defaultHash]);
    }
    
    // Verificación final
    const catsResult = await sql('SELECT * FROM categories');
    const prodsResult = await sql('SELECT * FROM products');
    console.log("Categorías registradas:", catsResult.map(c => c.name));
    console.log("Productos registrados:", prodsResult.map(p => `${p.id}: ${p.name} (${p.category})`));
  } catch (error) {
    console.error("Error al inicializar la base de datos:", error);
    process.exit(1);
  }
}

run();
